version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '80:5000'
    environment:
      - PORT=5000
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
      - DATABASE_NAME=ColorSurvey
      - DATABASE_USER=root
      - DATABASE_PASSWORD=test
      - DATABASE_SYNC=true
      - DATABASE_LOGGING=true
    volumes:
      - ./src:/app/src:ro
      - ./libs:/app/libs:ro
  database:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=ColorSurvey
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    cap_add:
      - SYS_NICE
    volumes:
      - ./database:/var/lib/mysql
